version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DATABASE_DB}
      - DATABASE_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: