version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: