# Generated by Django 5.1.7 on 2025-03-18 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 3, 18, 22, 10, 59, 29161, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
