# Generated by Django 5.1.7 on 2025-03-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0004_delete_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name': 'Kategoriyalar1', 'verbose_name_plural': 'Kategoriyar2'},
        ),
    ]
