# Generated by Django 5.1.7 on 2025-03-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_recipe_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
