# Generated by Django 5.1.7 on 2025-03-24 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipes_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(default=datetime.datetime(2025, 3, 24, 11, 59, 56, 467059, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
